config/routes.rb
Login::Application.routes.draw do
  resources :requests

  resources :vacancies

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
   @user = current_user
  end

  def help
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>This site is a one stop solution for all the cab booking and cab sharing problems we have been facing in the campus.Now you need not worry about going anywhere alone as you can easily find other students who have same plans like you.Here you can collaborate and plan your travel.</p>
<p>If you have already booked a cab and you have vacant seats then post a vacancy</p>
<p>If have plans to go somewhere and haven't booked a cab yet then post a Request mentioning your current group size</p>
<p>For any queries contact Arvind Allamneni at +91-9772211572</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<!DOCTYPE html>
<html>
  <head>
    <title>ChalkSpace | <%= yield(:title) %></title>
  </head>
  <body>
    
      <% if signed_in? %>
      
       <h1>Hello <%= @user.name %></h1>
      <%= link_to 'Post a Request', new_request_path %><br>
      <%= link_to 'Post a Vacancy', new_vacancy_path %>
      
      <% else %>
      <div class="center hero-unit">
      <h1>Welcome to Project Cabby</h1>

      <h2>
      This is the home page for our beta application.<br>
     </h2>
     <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-success" %>
     </div>
     <% end %>
   
  </body>
</html>