config/routes.rb
Login::Application.routes.draw do
  resources :requests

  resources :vacancies

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  

end

app/models/vacancy.rb
class Vacancy < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :start_at, presence: true
  validates :vacanctseats, presence: true
  validates :vehicle, presence: true, length: { maximum: 20 }
  validates :user_id, presence: true
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  before_action :signed_in_user
  before_action :set_vacancy, only: [:show, :edit, :update, :destroy]

  # GET /vacancies
  # GET /vacancies.json
  def index
    @user = current_user
    #@vacancies = @user.vacancies.paginate(page: params[:page])
    @vacancies = @user.vacancies.all
  end

  # GET /vacancies/1
  # GET /vacancies/1.json
  def show
  end

  # GET /vacancies/new
  def new
    @vacancy = Vacancy.new
  end

  # GET /vacancies/1/edit
  def edit
  end

  # POST /vacancies
  # POST /vacancies.json
  def create
    @vacancy = Vacancy.new(vacancy_params)
    @vacancy.user_id=current_user.id

    respond_to do |format|
      if @vacancy.save
        format.html { redirect_to @vacancy, notice: 'Vacancy was successfully created.' }
        format.json { render action: 'show', status: :created, location: @vacancy }
      else
        format.html { render action: 'new' }
        format.json { render json: @vacancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacancies/1
  # PATCH/PUT /vacancies/1.json
  def update
    respond_to do |format|
      if @vacancy.update(vacancy_params)
        format.html { redirect_to @vacancy, notice: 'Vacancy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @vacancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacancies/1
  # DELETE /vacancies/1.json
  def destroy
    @vacancy.destroy
    respond_to do |format|
      format.html { redirect_to vacancies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacancy
      @vacancy = Vacancy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vacancy_params
      params.require(:vacancy).permit(:start_at, :vehicle, :vacanctseats, :comments, :user_id)
    end
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
end

app/views/vacancies/_form.html.erb
<%= form_for(@vacancy) do |f| %>
  <% if @vacancy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vacancy.errors.count, "error") %> prohibited this vacancy from being saved:</h2>

      <ul>
      <% @vacancy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_at %><br>
    <%= f.datetime_select :start_at %>
  </div>
  <div class="field">
    <%= f.label :vehicle %><br>
    <%= f.text_field :vehicle %>
  </div>
  <div class="field">
    <%= f.label :vacanctseats %><br>
    <%= f.text_field :vacanctseats %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vacancies/edit.html.erb
<h1>Editing vacancy</h1>

<%= render 'form' %>

<%= link_to 'Show', @vacancy %> |
<%= link_to 'Back', vacancies_path %>

app/views/vacancies/index.html.erb
<h1>Listing vacancies</h1>

<table>
  <thead>
    <tr>
      <th>Start at</th>
      <th>Vehicle</th>
      <th>Vacanctseats</th>
      <th>Comments</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @vacancies.each do |vacancy| %>
      <tr>
        <td><%= vacancy.start_at %></td>
        <td><%= vacancy.vehicle %></td>
        <td><%= vacancy.vacanctseats %></td>
        <td><%= vacancy.comments %></td>
        <td><%= vacancy.user_id %></td>
        <td><%= link_to 'Show', vacancy %></td>
        <td><%= link_to 'Edit', edit_vacancy_path(vacancy) %></td>
        <td><%= link_to 'Destroy', vacancy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vacancy', new_vacancy_path %>

app/views/vacancies/new.html.erb
<h1>New vacancy</h1>

<%= render 'form' %>

<%= link_to 'Back', vacancies_path %>

app/views/vacancies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start at:</strong>
  <%= @vacancy.start_at %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @vacancy.vehicle %>
</p>

<p>
  <strong>Vacanctseats:</strong>
  <%= @vacancy.vacanctseats %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @vacancy.comments %>
</p>

<p>
  <strong>User:</strong>
  <%= @vacancy.user_id %>
</p>

<%= link_to 'Edit', edit_vacancy_path(@vacancy) %> |
<%= link_to 'Back', vacancies_path %>