config/routes.rb
Login::Application.routes.draw do
  resources :requests

  resources :vacancies

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  

end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :start_at, presence: true
  validates :destination, presence: true
  validates :group_size, presence: true
  validates :user_id, presence: true
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :signed_in_user
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  # GET /requests
  # GET /requests.json
  def index
    @user = current_user
    @requests = @user.requests.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)
    @request.user_id=current_user.id

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render action: 'show', status: :created, location: @request }
      else
        format.html { render action: 'new' }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:start_at, :destination, :group_size, :comments, :user_id)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_at %><br>
    <%= f.datetime_select :start_at %>
  </div>
  <div class="field">
    <%= f.label :destination %><br>
    <%= f.text_field :destination %>
  </div>
  <div class="field">
    <%= f.label :group_size %><br>
    <%= f.number_field :group_size %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<h1>Listing requests</h1>

<table>
  <thead>
    <tr>
      <th>Start at</th>
      <th>Destination</th>
      <th>Group size</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.start_at %></td>
        <td><%= request.destination %></td>
        <td><%= request.group_size %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Delete', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<h1>New request</h1>

<%= render 'form' %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start at:</strong>
  <%= @request.start_at %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @request.destination %>
</p>

<p>
  <strong>Group size:</strong>
  <%= @request.group_size %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @request.comments %>
</p>

<p>
  <strong>User:</strong>
  <%= @request.user_id %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>